<?php

return <<<'LANGUAGEFUNCTION'
function(b){function n(c){return c.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function D(c,h){var f=c&&c.exec(h);return f&&0===f.index}function r(c){var h,f={},b=Array.prototype.slice.call(arguments,1);for(h in c)f[h]=c[h];b.forEach(function(c){for(h in c)f[h]=c[h]});return f}function I(c){var h=[];(function d(c,b){for(var e=c.firstChild;e;e=e.nextSibling)3===e.nodeType?b+=e.nodeValue.length:1===e.nodeType&&(h.push({event:"start",offset:b,node:e}),b=d(e,b),e.nodeName.toLowerCase().match(/br|hr|img|input/)||
h.push({event:"stop",offset:b,node:e}));return b})(c,0);return h}function P(c,b,f){function e(){return c.length&&b.length?c[0].offset!==b[0].offset?c[0].offset<b[0].offset?c:b:"start"===b[0].event?c:b:c.length?c:b}function h(c){u+="<"+c.nodeName.toLowerCase()+J.map.call(c.attributes,function(c){return" "+c.nodeName+'="'+n(c.value).replace('"',"&quot;")+'"'}).join("")+">"}function d(c){u+="</"+c.nodeName.toLowerCase()+">"}function w(c){("start"===c.event?h:d)(c.node)}for(var v=0,u="",p=[];c.length||
b.length;){var g=e();u+=n(f.substring(v,g[0].offset));v=g[0].offset;if(g===c){p.reverse().forEach(d);do w(g.splice(0,1)[0]),g=e();while(g===c&&g.length&&g[0].offset===v);p.reverse().forEach(h)}else"start"===g[0].event?p.push(g[0].node):p.pop(),w(g.splice(0,1)[0])}return u+n(f.substr(v))}function Q(c){c.variants&&!c.cached_variants&&(c.cached_variants=c.variants.map(function(b){return r(c,{variants:null},b)}));return c.cached_variants||c.endsWithParent&&[r(c)]||[c]}function K(c){if(x&&!c.langApiRestored){c.langApiRestored=
!0;for(var b in x)c[b]&&(c[x[b]]=c[b]);(c.contains||[]).concat(c.variants||[]).forEach(K)}}function R(c){function b(c){return c&&c.source||c}function f(d,e){return new RegExp(b(d),"m"+(c.case_insensitive?"i":"")+(e?"g":""))}function e(c,e){for(var d=/\[(?:[^\\\]]|\\.)*\]|\(\??|\\([1-9][0-9]*)|\\./,f=0,h="",g=0;g<c.length;g++){var k=f,m=b(c[g]);for(0<g&&(h+=e);0<m.length;){var l=d.exec(m);if(null==l){h+=m;break}h+=m.substring(0,l.index);m=m.substring(l.index+l[0].length);"\\"==l[0][0]&&l[1]?h+="\\"+
String(Number(l[1])+k):(h+=l[0],"("==l[0]&&f++)}}return h}function k(d,h){if(!d.compiled){d.compiled=!0;d.keywords=d.keywords||d.beginKeywords;if(d.keywords){var n={},q=function(b,d){c.case_insensitive&&(d=d.toLowerCase());d.split(" ").forEach(function(c){c=c.split("|");n[c[0]]=[b,c[1]?Number(c[1]):1]})};"string"===typeof d.keywords?q("keyword",d.keywords):E(d.keywords).forEach(function(c){q(c,d.keywords[c])});d.keywords=n}d.lexemesRe=f(d.lexemes||/\w+/,!0);h&&(d.beginKeywords&&(d.begin="\\b("+d.beginKeywords.split(" ").join("|")+
")\\b"),d.begin||(d.begin=/\B|\b/),d.beginRe=f(d.begin),d.endSameAsBegin&&(d.end=d.begin),d.end||d.endsWithParent||(d.end=/\B|\b/),d.end&&(d.endRe=f(d.end)),d.terminator_end=b(d.end)||"",d.endsWithParent&&h.terminator_end&&(d.terminator_end+=(d.end?"|":"")+h.terminator_end));d.illegal&&(d.illegalRe=f(d.illegal));null==d.relevance&&(d.relevance=1);d.contains||(d.contains=[]);d.contains=Array.prototype.concat.apply([],d.contains.map(function(c){return Q("self"===c?d:c)}));d.contains.forEach(function(c){k(c,
d)});d.starts&&k(d.starts,h);var p=d.contains.map(function(c){return c.beginKeywords?"\\.?(?:"+c.begin+")\\.?":c.begin}).concat([d.terminator_end,d.illegal]).map(b).filter(Boolean);d.terminators=p.length?f(e(p,"|"),!0):{exec:function(){return null}}}}k(c)}function B(c,b,f,e){function h(c,b){if(D(c.endRe,b)){for(;c.endsParent&&c.parent;)c=c.parent;return c}if(c.endsWithParent)return h(c.parent,b)}function d(c,b,d,e){return c?'<span class="'+(e?"":q.classPrefix)+(c+'">')+b+(d?"":"</span>"):b}function w(){var c=
m,b;if(null!=g.subLanguage)if((b="string"===typeof g.subLanguage)&&!y[g.subLanguage])b=n(l);else{var e=b?B(g.subLanguage,l,!0,t[g.subLanguage]):G(l,g.subLanguage.length?g.subLanguage:void 0);0<g.relevance&&(r+=e.relevance);b&&(t[g.subLanguage]=e.top);b=d(e.language,e.value,!1,!0)}else if(g.keywords){e="";var f=0;g.lexemesRe.lastIndex=0;for(b=g.lexemesRe.exec(l);b;){e+=n(l.substring(f,b.index));f=g;var h=b;h=p.case_insensitive?h[0].toLowerCase():h[0];(f=f.keywords.hasOwnProperty(h)&&f.keywords[h])?
(r+=f[1],e+=d(f[0],n(b[0]))):e+=n(b[0]);f=g.lexemesRe.lastIndex;b=g.lexemesRe.exec(l)}b=e+n(l.substr(f))}else b=n(l);m=c+b;l=""}function v(c){m+=c.className?d(c.className,"",!0):"";g=Object.create(c,{parent:{value:g}})}function u(c,b){l+=c;if(null==b)return w(),0;a:{var d=g;var e;var k=0;for(e=d.contains.length;k<e;k++)if(D(d.contains[k].beginRe,b)){d.contains[k].endSameAsBegin&&(d.contains[k].endRe=new RegExp(d.contains[k].beginRe.exec(b)[0].replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"),"m"));d=d.contains[k];
break a}d=void 0}if(d)return d.skip?l+=b:(d.excludeBegin&&(l+=b),w(),d.returnBegin||d.excludeBegin||(l=b)),v(d,b),d.returnBegin?0:b.length;if(d=h(g,b)){k=g;k.skip?l+=b:(k.returnEnd||k.excludeEnd||(l+=b),w(),k.excludeEnd&&(l=b));do g.className&&(m+="</span>"),g.skip||g.subLanguage||(r+=g.relevance),g=g.parent;while(g!==d.parent);d.starts&&(d.endSameAsBegin&&(d.starts.endRe=d.endRe),v(d.starts,""));return k.returnEnd?0:b.length}if(!f&&D(g.illegalRe,b))throw Error('Illegal lexeme "'+b+'" for mode "'+
(g.className||"<unnamed>")+'"');l+=b;return b.length||1}var p=z(c);if(!p)throw Error('Unknown language: "'+c+'"');R(p);var g=e||p,t={},m="";for(e=g;e!==p;e=e.parent)e.className&&(m=d(e.className,"",!0)+m);var l="",r=0;try{for(var A,x,C=0;;){g.terminators.lastIndex=C;A=g.terminators.exec(b);if(!A)break;x=u(b.substring(C,A.index),A[0]);C=A.index+x}u(b.substr(C));for(e=g;e.parent;e=e.parent)e.className&&(m+="</span>");return{relevance:r,value:m,language:c,top:g}}catch(F){if(F.message&&-1!==F.message.indexOf("Illegal"))return{relevance:0,
value:n(b)};throw F;}}function G(c,b){b=b||q.languages||E(y);var f={relevance:0,value:n(c)},e=f;b.filter(z).filter(L).forEach(function(b){var d=B(b,c,!1);d.language=b;d.relevance>e.relevance&&(e=d);d.relevance>f.relevance&&(e=f,f=d)});e.language&&(f.second_best=e);return f}function M(c){return q.tabReplace||q.useBR?c.replace(S,function(c,b){return q.useBR&&"\n"===c?"<br>":q.tabReplace?b.replace(/\t/g,q.tabReplace):""}):c}function N(c){var b,f;a:{var e=c.className+" ";e+=c.parentNode?c.parentNode.className:
"";if(f=T.exec(e))f=z(f[1])?f[1]:"no-highlight";else{e=e.split(/\s+/);f=0;for(b=e.length;f<b;f++){var k=e[f];if(O.test(k)||z(k)){f=k;break a}}f=void 0}}if(!O.test(f)){q.useBR?(k=document.createElementNS("http://www.w3.org/1999/xhtml","div"),k.innerHTML=c.innerHTML.replace(/\n/g,"").replace(/<br[ \/]*>/g,"\n")):k=c;b=k.textContent;e=f?B(f,b,!0):G(b);k=I(k);if(k.length){var d=document.createElementNS("http://www.w3.org/1999/xhtml","div");d.innerHTML=e.value;e.value=P(k,I(d),b)}e.value=M(e.value);c.innerHTML=
e.value;b=c.className;f=f?H[f]:e.language;k=[b.trim()];b.match(/\bhljs\b/)||k.push("hljs");-1===b.indexOf(f)&&k.push(f);f=k.join(" ").trim();c.className=f;c.result={language:e.language,re:e.relevance};e.second_best&&(c.second_best={language:e.second_best.language,re:e.second_best.relevance})}}function t(){if(!t.called){t.called=!0;var b=document.querySelectorAll("pre code");J.forEach.call(b,N)}}function z(b){b=(b||"").toLowerCase();return y[b]||y[H[b]]}function L(b){return(b=z(b))&&!b.disableAutodetect}
var J=[],E=Object.keys,y={},H={},O=/^(no-?highlight|plain|text)$/i,T=/\blang(?:uage)?-([\w-]+)\b/i,S=/((^(<[^>]+>|\t|)+|(?:\n)))/gm,x,q={classPrefix:"hljs-",tabReplace:null,useBR:!1,languages:void 0};b.highlight=B;b.highlightAuto=G;b.fixMarkup=M;b.highlightBlock=N;b.configure=function(b){q=r(q,b)};b.initHighlighting=t;b.initHighlightingOnLoad=function(){addEventListener("DOMContentLoaded",t,!1);addEventListener("load",t,!1)};b.registerLanguage=function(c,h){var f=y[c]=h(b);K(f);f.aliases&&f.aliases.forEach(function(b){H[b]=
c})};b.listLanguages=function(){return E(y)};b.getLanguage=z;b.autoDetection=L;b.inherit=r;b.IDENT_RE="[a-zA-Z]\\w*";b.UNDERSCORE_IDENT_RE="[a-zA-Z_]\\w*";b.NUMBER_RE="\\b\\d+(\\.\\d+)?";b.C_NUMBER_RE="(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";b.BINARY_NUMBER_RE="\\b(0b[01]+)";b.RE_STARTERS_RE="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|-|-=|/=|/|:|;|<<|<<=|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";b.BACKSLASH_ESCAPE={begin:"\\\\[\\s\\S]",
relevance:0};b.APOS_STRING_MODE={className:"string",begin:"'",end:"'",illegal:"\\n",contains:[b.BACKSLASH_ESCAPE]};b.QUOTE_STRING_MODE={className:"string",begin:'"',end:'"',illegal:"\\n",contains:[b.BACKSLASH_ESCAPE]};b.PHRASAL_WORDS_MODE={begin:/\b(a|an|the|are|I'm|isn't|don't|doesn't|won't|but|just|should|pretty|simply|enough|gonna|going|wtf|so|such|will|you|your|they|like|more)\b/};b.COMMENT=function(c,h,f){c=b.inherit({className:"comment",begin:c,end:h,contains:[]},f||{});c.contains.push(b.PHRASAL_WORDS_MODE);
c.contains.push({className:"doctag",begin:"(?:TODO|FIXME|NOTE|BUG|XXX):",relevance:0});return c};b.C_LINE_COMMENT_MODE=b.COMMENT("//","$");b.C_BLOCK_COMMENT_MODE=b.COMMENT("/\\*","\\*/");b.HASH_COMMENT_MODE=b.COMMENT("#","$");b.NUMBER_MODE={className:"number",begin:b.NUMBER_RE,relevance:0};b.C_NUMBER_MODE={className:"number",begin:b.C_NUMBER_RE,relevance:0};b.BINARY_NUMBER_MODE={className:"number",begin:b.BINARY_NUMBER_RE,relevance:0};b.CSS_NUMBER_MODE={className:"number",begin:b.NUMBER_RE+"(%|em|ex|ch|rem|vw|vh|vmin|vmax|cm|mm|in|pt|pc|px|deg|grad|rad|turn|s|ms|Hz|kHz|dpi|dpcm|dppx)?",
relevance:0};b.REGEXP_MODE={className:"regexp",begin:/\//,end:/\/[gimuy]*/,illegal:/\n/,contains:[b.BACKSLASH_ESCAPE,{begin:/\[/,end:/\]/,relevance:0,contains:[b.BACKSLASH_ESCAPE]}]};b.TITLE_MODE={className:"title",begin:b.IDENT_RE,relevance:0};b.UNDERSCORE_TITLE_MODE={className:"title",begin:b.UNDERSCORE_IDENT_RE,relevance:0};b.METHOD_GUARD={begin:"\\.\\s*"+b.UNDERSCORE_IDENT_RE,relevance:0};return b};
LANGUAGEFUNCTION;
