<?php

return <<<'LANGUAGEFUNCTION'
function(b){var g={keyword:"abstract as val var vararg get set class object open private protected public noinline crossinline dynamic final enum if else do while for when throw try catch finally import package is in fun override companion reified inline lateinit init interface annotation data sealed internal infix operator out by constructor super tailrec where const inner suspend typealias external expect actual trait volatile transient native default",built_in:"Byte Short Char Int Long Boolean Float Double Void Unit Nothing",
literal:"true false null"},k={className:"symbol",begin:b.UNDERSCORE_IDENT_RE+"@"},c={className:"subst",begin:"\\${",end:"}",contains:[b.APOS_STRING_MODE,b.C_NUMBER_MODE]},d={className:"variable",begin:"\\$"+b.UNDERSCORE_IDENT_RE};c={className:"string",variants:[{begin:'"""',end:'"""',contains:[d,c]},{begin:"'",end:"'",illegal:/\n/,contains:[b.BACKSLASH_ESCAPE]},{begin:'"',end:'"',illegal:/\n/,contains:[b.BACKSLASH_ESCAPE,d,c]}]};d={className:"meta",begin:"@(?:file|property|field|get|set|receiver|param|setparam|delegate)\\s*:(?:\\s*"+
b.UNDERSCORE_IDENT_RE+")?"};var h={className:"meta",begin:"@"+b.UNDERSCORE_IDENT_RE,contains:[{begin:/\(/,end:/\)/,contains:[b.inherit(c,{className:"meta-string"})]}]},f=b.COMMENT("/\\*","\\*/",{contains:[b.C_BLOCK_COMMENT_MODE]}),e={variants:[{className:"type",begin:b.UNDERSCORE_IDENT_RE},{begin:/\(/,end:/\)/,contains:[]}]};e.variants[1].contains=[e];e.variants[1].contains=[e];return{aliases:["kt"],keywords:g,contains:[b.COMMENT("/\\*\\*","\\*/",{relevance:0,contains:[{className:"doctag",begin:"@[A-Za-z]+"}]}),
b.C_LINE_COMMENT_MODE,f,{className:"keyword",begin:/\b(break|continue|return|this)\b/,starts:{contains:[{className:"symbol",begin:/@\w+/}]}},k,d,h,{className:"function",beginKeywords:"fun",end:"[(]|$",returnBegin:!0,excludeEnd:!0,keywords:g,illegal:/fun\s+(<.*>)?[^\s\(]+(\s+[^\s\(]+)\s*=/,relevance:5,contains:[{begin:b.UNDERSCORE_IDENT_RE+"\\s*\\(",returnBegin:!0,relevance:0,contains:[b.UNDERSCORE_TITLE_MODE]},{className:"type",begin:/</,end:/>/,keywords:"reified",relevance:0},{className:"params",
begin:/\(/,end:/\)/,endsParent:!0,keywords:g,relevance:0,contains:[{begin:/:/,end:/[=,\/]/,endsWithParent:!0,contains:[e,b.C_LINE_COMMENT_MODE,f],relevance:0},b.C_LINE_COMMENT_MODE,f,d,h,c,b.C_NUMBER_MODE]},f]},{className:"class",beginKeywords:"class interface trait",end:/[:\{(]|$/,excludeEnd:!0,illegal:"extends implements",contains:[{beginKeywords:"public protected internal private constructor"},b.UNDERSCORE_TITLE_MODE,{className:"type",begin:/</,end:/>/,excludeBegin:!0,excludeEnd:!0,relevance:0},
{className:"type",begin:/[,:]\s*/,end:/[<\(,]|$/,excludeBegin:!0,returnEnd:!0},d,h]},c,{className:"meta",begin:"^#!/usr/bin/env",end:"$",illegal:"\n"},{className:"number",begin:"\\b(0[bB]([01]+[01_]+[01]+|[01]+)|0[xX]([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)|(([\\d]+[\\d_]+[\\d]+|[\\d]+)(\\.([\\d]+[\\d_]+[\\d]+|[\\d]+))?|\\.([\\d]+[\\d_]+[\\d]+|[\\d]+))([eE][-+]?\\d+)?)[lLfF]?",relevance:0}]}};
LANGUAGEFUNCTION;
