<?php

return <<<'LANGUAGEFUNCTION'
function(b){var c={keyword:"in if for while finally var new function do return void else break catch instanceof with throw case default try this switch continue typeof delete let yield const class public private protected get set super static implements enum export import declare type namespace abstract as from extends async await",literal:"true false null undefined NaN Infinity",built_in:"eval isFinite isNaN parseFloat parseInt decodeURI decodeURIComponent encodeURI encodeURIComponent escape unescape Object Function Boolean Error EvalError InternalError RangeError ReferenceError StopIteration SyntaxError TypeError URIError Number Math Date String RegExp Array Float32Array Float64Array Int16Array Int32Array Int8Array Uint16Array Uint32Array Uint8Array Uint8ClampedArray ArrayBuffer DataView JSON Intl arguments require module console window document any number boolean string void Promise"},
e={className:"meta",begin:"@[A-Za-z$_][0-9A-Za-z$_]*"},f={begin:"\\(",end:/\)/,keywords:c,contains:["self",b.QUOTE_STRING_MODE,b.APOS_STRING_MODE,b.NUMBER_MODE]},g={className:"params",begin:/\(/,end:/\)/,excludeBegin:!0,excludeEnd:!0,keywords:c,contains:[b.C_LINE_COMMENT_MODE,b.C_BLOCK_COMMENT_MODE,e,f]},h={className:"number",variants:[{begin:"\\b(0[bB][01]+)"},{begin:"\\b(0[oO][0-7]+)"},{begin:b.C_NUMBER_RE}],relevance:0},d={className:"subst",begin:"\\$\\{",end:"\\}",keywords:c,contains:[]},k={begin:"html`",
end:"",starts:{end:"`",returnEnd:!1,contains:[b.BACKSLASH_ESCAPE,d],subLanguage:"xml"}},l={begin:"css`",end:"",starts:{end:"`",returnEnd:!1,contains:[b.BACKSLASH_ESCAPE,d],subLanguage:"css"}},m={className:"string",begin:"`",end:"`",contains:[b.BACKSLASH_ESCAPE,d]};d.contains=[b.APOS_STRING_MODE,b.QUOTE_STRING_MODE,k,l,m,h,b.REGEXP_MODE];return{aliases:["ts"],keywords:c,contains:[{className:"meta",begin:/^\s*['"]use strict['"]/},b.APOS_STRING_MODE,b.QUOTE_STRING_MODE,k,l,m,b.C_LINE_COMMENT_MODE,b.C_BLOCK_COMMENT_MODE,
h,{begin:"("+b.RE_STARTERS_RE+"|\\b(case|return|throw)\\b)\\s*",keywords:"return throw case",contains:[b.C_LINE_COMMENT_MODE,b.C_BLOCK_COMMENT_MODE,b.REGEXP_MODE,{className:"function",begin:"(\\(.*?\\)|"+b.IDENT_RE+")\\s*=>",returnBegin:!0,end:"\\s*=>",contains:[{className:"params",variants:[{begin:b.IDENT_RE},{begin:/\(\s*\)/},{begin:/\(/,end:/\)/,excludeBegin:!0,excludeEnd:!0,keywords:c,contains:["self",b.C_LINE_COMMENT_MODE,b.C_BLOCK_COMMENT_MODE]}]}]}],relevance:0},{className:"function",begin:"function",
end:/[\{;]/,excludeEnd:!0,keywords:c,contains:["self",b.inherit(b.TITLE_MODE,{begin:"[A-Za-z$_][0-9A-Za-z$_]*"}),g],illegal:/%/,relevance:0},{beginKeywords:"constructor",end:/\{/,excludeEnd:!0,contains:["self",g]},{begin:/module\./,keywords:{built_in:"module"},relevance:0},{beginKeywords:"module",end:/\{/,excludeEnd:!0},{beginKeywords:"interface",end:/\{/,excludeEnd:!0,keywords:"interface extends"},{begin:/\$[(.]/},{begin:"\\."+b.IDENT_RE,relevance:0},e,f]}};
LANGUAGEFUNCTION;
